# shellforge/generate.py
"""Assemble a case on disk: evidence, ground truth, reference copy.

The layout is the one Shellhound expects to be pointed at, so registering a
generated case is three paths and no explanation:

    <out>/<slug>/
        webroot/          the compromised installation
        reference/        the same release, clean -- enables the webroot diff
        logs/             access.log[.N[.gz]], error.log
        dump.sql
        ground_truth.json what a correct detector must say about all of it
        hunt_patterns.json  patterns this case is meant to be searched with
        README.md         the case in prose, for whoever opens the directory
"""
from __future__ import annotations

import hashlib
import json
from pathlib import Path

from shellforge import scenarios
from shellforge.render import accesslog, errorlog, sqldump, webroot
from shellforge.rng import Rng
from shellforge.world import wordpress

WORLDS = {"wordpress": wordpress}


def _slug(scenario: str, seed: int, scale: str) -> str:
    return f"{scenario}-{scale}-{seed}"


def generate(*, scenario: str, cms: str = "wordpress", seed: int = 1,
             scale: str = "small", out: Path, log_format: str = "apache",
             rotate_days: int = 0, verify: bool = True) -> dict:
    if cms not in WORLDS:
        raise KeyError(f"unknown cms {cms!r}; have: {', '.join(WORLDS)}")

    rng = Rng(seed)
    site = WORLDS[cms].build(rng.derive("world"), scale)
    case = scenarios.get(scenario)(rng.derive("scenario"), site, scale)

    case_dir = Path(out) / _slug(scenario, seed, scale)
    case_dir.mkdir(parents=True, exist_ok=True)

    # --- evidence -----------------------------------------------------------
    digests = webroot.write(case_dir / "webroot", case.files, verify=verify)

    # The clean side of the diff: the same installation minus what the attack
    # added, with the originals restored where it overwrote something.
    clean = webroot.reference_copy(case.files, case.added_paths)
    clean.update(case.modified)
    webroot.write(case_dir / "reference", clean, verify=verify)

    log_files = accesslog.write(case_dir / "logs", case.requests,
                                fmt=log_format, rotate_days=rotate_days)
    if case.error_lines:
        errorlog.write(case_dir / "logs", case.error_lines)
    sqldump.write(case_dir / "dump.sql", site, extra_rows=case.extra_rows)

    # --- ground truth -------------------------------------------------------
    # Digests are filled in AFTER writing, from what actually landed on disk.
    # A hash computed from the intended content would still be correct in a
    # case where the scanner ate the file, which is exactly when it matters.
    for planted in case.truth.planted:
        if planted.kind == "file":
            rel = planted.ident.lstrip("/")
            planted.sha256 = digests.get(rel, "")
    case.truth.write(case_dir / "ground_truth.json")

    (case_dir / "hunt_patterns.json").write_text(
        json.dumps({"patterns": case.hunt_patterns}, indent=2,
                   ensure_ascii=False) + "\n", encoding="utf-8")

    summary = {
        "case_dir": str(case_dir),
        "scenario": scenario, "cms": cms, "seed": seed, "scale": scale,
        "files": len(case.files),
        "requests": len(case.requests),
        "error_lines": len(case.error_lines),
        "log_files": [p.name for p in log_files],
        "planted": len(case.truth.planted),
        "must_not_fire": len(case.truth.must_not_fire),
        "expected_rules": sorted(case.truth.expected_rule_ids()),
        # A fingerprint of the whole case. Two runs of the same seed must
        # produce the same value; if they do not, something unseeded crept in.
        "digest": hashlib.sha256(
            "".join(f"{k}:{v}" for k, v in sorted(digests.items()))
            .encode()).hexdigest()[:16],
    }
    (case_dir / "README.md").write_text(_readme(case, summary),
                                        encoding="utf-8")
    return summary


def _readme(case, summary) -> str:
    truth = case.truth
    lines = [
        f"# {summary['scenario']} | seed {summary['seed']} | {summary['scale']}",
        "",
        "Generated by Shellforge. Everything in here is invented: addresses "
        "come from the documentation ranges of RFC 5737, domains end in "
        "`.test`, and every payload is an inert marker that carries a pattern "
        "and does nothing.",
        "",
        "## Register in Shellhound",
        "",
        "| Evidence | Path |",
        "|---|---|",
        f"| Webroot | `webroot/` |",
        f"| Access logs | `logs/` |",
        f"| SQL dump | `dump.sql` |",
        f"| Reference copy | `reference/` |",
        "",
        "## Size",
        "",
        f"- {summary['files']} files in the webroot",
        f"- {summary['requests']} log lines across "
        f"{len(summary['log_files'])} file(s)",
        f"- {summary['error_lines']} error-log lines",
        f"- case digest `{summary['digest']}` "
        f"(same seed must give the same value)",
        "",
        "## What a correct detector must say",
        "",
        f"{len(truth.planted)} planted objects, "
        f"{len(truth.must_not_fire)} silence assertions. Full detail in "
        "`ground_truth.json`; score a scanned case with:",
        "",
        "```bash",
        f"shellforge score --truth ground_truth.json --case <shellhound-case>/case.db",
        "```",
        "",
        "| Object | Must produce |",
        "|---|---|",
    ]
    for planted in truth.planted:
        lines.append(f"| `{planted.ident}` | "
                     f"{', '.join(planted.expect_rules)} |")
    lines += ["", "## Timeline", ""]
    for event in sorted(truth.timeline, key=lambda e: e.at):
        lines.append(f"- `{event.at}` **{event.act}** "
                     f"({event.actor}) {event.detail}")
    if truth.notes:
        lines += ["", "## Notes", ""]
        lines += [f"- {n}" for n in truth.notes]
    return "\n".join(lines) + "\n"
